import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'personas',
        path: '/personas',
        title: 'Personas',
        translateKey: 'nav.personas',
        icon: 'users',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'productos',
        path: '/productos',
        title: 'Productos',
        translateKey: 'nav.productos',
        icon: 'product',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'servicios',
        path: '/servicios',
        title: 'Servicios',
        translateKey: 'nav.servicios',
        icon: 'briefcase',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'presupuestos',
        path: '/presupuestos',
        title: 'Presupuestos',
        translateKey: 'nav.presupuestos',
        icon: 'document',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'gestion',
        path: '',
        title: 'Gestión Comercial',
        translateKey: 'nav.gestion.title',
        icon: 'briefcase',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'gestion.clientes',
                path: '/personas?tipo=CLIENTE',
                title: 'Clientes',
                translateKey: 'nav.gestion.clientes',
                icon: 'userGroup',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestion.proveedores',
                path: '/personas?tipo=PROVEEDOR',
                title: 'Proveedores',
                translateKey: 'nav.gestion.proveedores',
                icon: 'truck',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestion.servicios',
                path: '/servicios',
                title: 'Servicios',
                translateKey: 'nav.gestion.servicios',
                icon: 'cog',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'facturacion',
        path: '',
        title: 'Facturación',
        translateKey: 'nav.facturacion.title',
        icon: 'calculator',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'facturacion.facturas',
                path: '/facturas',
                title: 'Facturas',
                translateKey: 'nav.facturacion.facturas',
                icon: 'invoice',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'facturacion.recibos',
                path: '/recibos',
                title: 'Recibos',
                translateKey: 'nav.facturacion.recibos',
                icon: 'receipt',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'facturacion.impuestos',
                path: '/impuestos',
                title: 'Impuestos',
                translateKey: 'nav.facturacion.impuestos',
                icon: 'percentage',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
