import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    // Personas oculto - Se accede via Clientes/Proveedores
    // {
    //     key: 'personas',
    //     path: '/personas',
    //     title: 'Personas',
    //     translateKey: 'nav.personas',
    //     icon: 'users',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    {
        key: 'productos',
        path: '/productos',
        title: 'Productos',
        translateKey: 'nav.productos',
        icon: 'product',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'servicios',
        path: '/servicios',
        title: 'Servicios',
        translateKey: 'nav.servicios',
        icon: 'briefcase',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'presupuestos',
        path: '/presupuestos',
        title: 'Presupuestos',
        translateKey: 'nav.presupuestos',
        icon: 'presupuesto',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'gestion',
        path: '',
        title: 'Gestión Comercial',
        translateKey: 'nav.gestion.title',
        icon: 'briefcase',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'gestion.clientes',
                path: '/personas?tipo=CLIENTE',
                title: 'Clientes',
                translateKey: 'nav.gestion.clientes',
                icon: 'userGroup',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestion.clientes.nuevo',
                path: '/personas/cliente/new',
                title: 'Nuevo Cliente',
                translateKey: 'nav.gestion.nuevoCliente',
                icon: 'userAdd',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestion.proveedores',
                path: '/personas?tipo=PROVEEDOR',
                title: 'Proveedores',
                translateKey: 'nav.gestion.proveedores',
                icon: 'truck',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestion.proveedores.nuevo',
                path: '/personas/proveedor/new',
                title: 'Nuevo Proveedor',
                translateKey: 'nav.gestion.nuevoProveedor',
                icon: 'buildingAdd',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'gestion.usuarios.interno',
                path: '/personas/interno/new',
                title: 'Nuevo Usuario Interno',
                translateKey: 'nav.gestion.nuevoInterno',
                icon: 'userPlus',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'], // Solo admins pueden crear usuarios internos
                subMenu: [],
            },
            {
                key: 'gestion.servicios',
                path: '/servicios',
                title: 'Servicios',
                translateKey: 'nav.gestion.servicios',
                icon: 'cog',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'facturacion',
        path: '',
        title: 'Facturación',
        translateKey: 'nav.facturacion.title',
        icon: 'calculator',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'facturacion.facturas',
                path: '/facturas',
                title: 'Facturas',
                translateKey: 'nav.facturacion.facturas',
                icon: 'invoice',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'facturacion.recibos',
                path: '/recibos',
                title: 'Recibos',
                translateKey: 'nav.facturacion.recibos',
                icon: 'receipt',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'facturacion.impuestos',
                path: '/impuestos',
                title: 'Impuestos',
                translateKey: 'nav.facturacion.impuestos',
                icon: 'percentage',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'facturacion.monedas',
                path: '/monedas',
                title: 'Monedas',
                translateKey: 'nav.facturacion.monedas',
                icon: 'currency',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'finanzas',
        path: '',
        title: 'Finanzas y Costos',
        translateKey: 'nav.finanzas.title',
        icon: 'chartLine',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'finanzas.gastos',
                path: '/gastos',
                title: 'Gastos Operativos',
                translateKey: 'nav.finanzas.gastos',
                icon: 'cash',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'finanzas.gastos.nuevo',
                path: '/gastos/new',
                title: 'Nuevo Gasto',
                translateKey: 'nav.finanzas.nuevoGasto',
                icon: 'plus',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'finanzas.rentabilidad',
                path: '/gastos/rentabilidad',
                title: 'Análisis de Rentabilidad',
                translateKey: 'nav.finanzas.rentabilidad',
                icon: 'trendingUp',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
