import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    
    // === GESTIÓN DE CATÁLOGOS ===
    {
        key: 'catalogos',
        path: '',
        title: 'Catálogos',
        translateKey: 'nav.catalogos.title',
        icon: 'database',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'catalogos.productos',
                path: '/productos',
                title: 'Productos',
                translateKey: 'nav.catalogos.productos',
                icon: 'package',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'catalogos.servicios',
                path: '/servicios',
                title: 'Servicios',
                translateKey: 'nav.catalogos.servicios',
                icon: 'briefcase',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'catalogos.precios',
                path: '/historial-precios',
                title: 'Gestión de Precios',
                translateKey: 'nav.catalogos.precios',
                icon: 'chartBar',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    // === GESTIÓN COMERCIAL ===
    {
        key: 'comercial',
        path: '',
        title: 'Gestión Comercial',
        translateKey: 'nav.comercial.title',
        icon: 'briefcase',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'comercial.clientes',
                path: '/personas?tipo=CLIENTE',
                title: 'Clientes',
                translateKey: 'nav.comercial.clientes',
                icon: 'userGroup',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'comercial.empresas',
                path: '/empresas',
                title: 'Empresas',
                translateKey: 'nav.comercial.empresas',
                icon: 'building',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'comercial.proveedores',
                path: '/personas?tipo=PROVEEDOR',
                title: 'Proveedores',
                translateKey: 'nav.comercial.proveedores',
                icon: 'truck',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'comercial.presupuestos',
                path: '/presupuestos',
                title: 'Presupuestos',
                translateKey: 'nav.comercial.presupuestos',
                icon: 'calculator',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    // === OPERACIONES RÁPIDAS ===
    {
        key: 'operaciones',
        path: '',
        title: 'Operaciones Rápidas',
        translateKey: 'nav.operaciones.title',
        icon: 'lightning',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'operaciones.nuevo-cliente',
                path: '/personas/cliente/new',
                title: 'Nuevo Cliente con Empresa',
                translateKey: 'nav.operaciones.nuevoClienteConEmpresa',
                icon: 'userAdd',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'operaciones.nuevo-proveedor',
                path: '/personas/proveedor/new',
                title: 'Nuevo Proveedor',
                translateKey: 'nav.operaciones.nuevoProveedor',
                icon: 'buildingAdd',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'operaciones.nuevo-presupuesto',
                path: '/presupuestos/new',
                title: 'Nuevo Presupuesto',
                translateKey: 'nav.operaciones.nuevoPresupuesto',
                icon: 'documentAdd',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'operaciones.nuevo-gasto',
                path: '/gastos/new',
                title: 'Nuevo Gasto',
                translateKey: 'nav.operaciones.nuevoGasto',
                icon: 'receiptAdd',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'operaciones.nuevo-usuario',
                path: '/personas/interno/new',
                title: 'Nuevo Usuario Interno',
                translateKey: 'nav.operaciones.nuevoUsuario',
                icon: 'userPlus',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['ADMIN'], // Solo admins pueden crear usuarios internos
                subMenu: [],
            },
        ],
    },
    // === FACTURACIÓN ===
    {
        key: 'facturacion',
        path: '',
        title: 'Facturación',
        translateKey: 'nav.facturacion.title',
        icon: 'invoice',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'facturacion.facturas',
                path: '/facturas',
                title: 'Facturas',
                translateKey: 'nav.facturacion.facturas',
                icon: 'receipt',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'facturacion.recibos',
                path: '/recibos',
                title: 'Recibos',
                translateKey: 'nav.facturacion.recibos',
                icon: 'receiptTax',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    // === FINANZAS Y CONTROL ===
    {
        key: 'finanzas',
        path: '',
        title: 'Finanzas y Control',
        translateKey: 'nav.finanzas.title',
        icon: 'chartLine',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'finanzas.gastos',
                path: '/gastos',
                title: 'Gastos Operativos',
                translateKey: 'nav.finanzas.gastos',
                icon: 'cash',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'finanzas.rentabilidad',
                path: '/gastos/rentabilidad',
                title: 'Análisis de Rentabilidad',
                translateKey: 'nav.finanzas.rentabilidad',
                icon: 'trendingUp',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    // === CONFIGURACIÓN ===
    {
        key: 'configuracion',
        path: '',
        title: 'Configuración',
        translateKey: 'nav.configuracion.title',
        icon: 'cog',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'configuracion.monedas',
                path: '/monedas',
                title: 'Monedas',
                translateKey: 'nav.configuracion.monedas',
                icon: 'currency',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'configuracion.impuestos',
                path: '/impuestos',
                title: 'Impuestos',
                translateKey: 'nav.configuracion.impuestos',
                icon: 'percentage',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
